"""initial

Revision ID: 1150177c20ca
Revises: 
Create Date: 2026-03-26 03:44:48.356156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1150177c20ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias_financeiras',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_categoria', sa.Enum('ENTRADA', 'SAIDA', name='tipocategoriafinanceira'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', 'tipo_categoria', name='uq_categoria_financeira_tenant_nome_tipo')
    )
    with op.batch_alter_table('categorias_financeiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_financeiras_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('categorias_produto',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_categoria_produto_tenant_nome')
    )
    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_produto_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cupons',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('tipo_desconto', sa.Enum('PERCENTUAL', 'VALOR', name='tipodesconto'), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_cupom_tenant_codigo')
    )
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupons_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('empresas',
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=180), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=180), nullable=False),
    sa.Column('tipo_empresa', sa.Enum('MATRIZ', 'FILIAL', name='tipoempresa'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cnpj', name='uq_empresa_tenant_cnpj'),
    sa.UniqueConstraint('tenant_id', 'nome_fantasia', name='uq_empresa_tenant_nome_fantasia')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('formas_pagamento',
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_forma_pagamento_tenant_nome')
    )
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formas_pagamento_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('funcionarios',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cpf', name='uq_funcionario_tenant_cpf'),
    sa.UniqueConstraint('tenant_id', 'usuario', name='uq_funcionario_tenant_usuario')
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tipos_operacao',
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('tipo_operacao', sa.Enum('VENDA', 'ENTRADA_ESTOQUE', 'AJUSTE_ESTOQUE', 'TRANSFERENCIA', name='tipooperacaoenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_tipo_operacao_tenant_codigo'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_tipo_operacao_tenant_nome')
    )
    with op.batch_alter_table('tipos_operacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_operacao_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('fechamentos_caixa',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_fechamento', sa.Date(), nullable=False),
    sa.Column('valor_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_final', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'empresa_id', 'funcionario_id', 'data_fechamento', name='uq_fechamento_caixa_tenant_empresa_funcionario_data')
    )
    with op.batch_alter_table('fechamentos_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fechamentos_caixa_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('funcionarios_empresa',
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'funcionario_id', 'empresa_id', name='uq_funcionario_empresa')
    )
    with op.batch_alter_table('funcionarios_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_empresa_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('produtos',
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_funcionario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('possui_ncm', sa.Boolean(), nullable=False),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('codigo_barras', sa.String(length=60), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('possui_ncm = FALSE OR ncm IS NOT NULL', name='ck_produto_ncm_flag'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_produto.id'], ),
    sa.ForeignKeyConstraint(['criado_por_funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo_barras', name='uq_produto_tenant_codigo_barras'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_produto_tenant_nome')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('vendas',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_operacao_id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.Column('numero_unico', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'FINALIZADA', 'CANCELADA', name='statusvenda'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('desconto >= 0', name='ck_venda_desconto_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_venda_subtotal_non_negative'),
    sa.CheckConstraint('total >= 0', name='ck_venda_total_non_negative'),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacao_id'], ['tipos_operacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'empresa_id', 'numero_unico', name='uq_venda_tenant_empresa_numero_unico')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index('ix_venda_tenant_empresa_data', ['tenant_id', 'empresa_id', 'data_venda'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('itens_venda',
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_item_venda_quantidade_positive'),
    sa.CheckConstraint('valor_total >= 0', name='ck_item_venda_valor_total_non_negative'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_item_venda_valor_unitario_non_negative'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_venda_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lancamentos_financeiros',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipofinanceiro'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_lancamento', sa.DateTime(), nullable=False),
    sa.Column('data_competencia', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor >= 0', name='ck_lancamento_financeiro_valor_non_negative'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.create_index('ix_financeiro_tenant_empresa_data', ['tenant_id', 'empresa_id', 'data_lancamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('movimentos_estoque',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimento', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentoestoque'), nullable=False),
    sa.Column('motivo', sa.Enum('COMPRA', 'VENDA', 'AJUSTE', 'PERDA', 'DEVOLUCAO', 'TRANSFERENCIA', name='motivomovimentoestoque'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_movimento', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_movimento_estoque_quantidade_positive'),
    sa.CheckConstraint('valor_total IS NULL OR valor_total >= 0', name='ck_movimento_estoque_valor_total_non_negative'),
    sa.CheckConstraint('valor_unitario IS NULL OR valor_unitario >= 0', name='ck_movimento_estoque_valor_unitario_non_negative'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.create_index('ix_mov_estoque_tenant_empresa_produto', ['tenant_id', 'empresa_id', 'produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pagamentos_venda',
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comprovante', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor >= 0', name='ck_pagamento_venda_valor_non_negative'),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('produtos_empresa',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('valor_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('estoque_atual >= 0', name='ck_produto_empresa_estoque_atual_non_negative'),
    sa.CheckConstraint('estoque_minimo >= 0', name='ck_produto_empresa_estoque_minimo_non_negative'),
    sa.CheckConstraint('valor_compra >= 0', name='ck_produto_empresa_valor_compra_non_negative'),
    sa.CheckConstraint('valor_venda >= 0', name='ck_produto_empresa_valor_venda_non_negative'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'produto_id', 'empresa_id', name='uq_produto_empresa')
    )
    with op.batch_alter_table('produtos_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_empresa_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_empresa_tenant_id'))

    op.drop_table('produtos_empresa')
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_tenant_id'))

    op.drop_table('pagamentos_venda')
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_tenant_id'))
        batch_op.drop_index('ix_mov_estoque_tenant_empresa_produto')

    op.drop_table('movimentos_estoque')
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_tenant_id'))
        batch_op.drop_index('ix_financeiro_tenant_empresa_data')

    op.drop_table('lancamentos_financeiros')
    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_venda_tenant_id'))

    op.drop_table('itens_venda')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_tenant_id'))
        batch_op.drop_index('ix_venda_tenant_empresa_data')

    op.drop_table('vendas')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_tenant_id'))

    op.drop_table('produtos')
    with op.batch_alter_table('funcionarios_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_empresa_tenant_id'))

    op.drop_table('funcionarios_empresa')
    with op.batch_alter_table('fechamentos_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fechamentos_caixa_tenant_id'))

    op.drop_table('fechamentos_caixa')
    with op.batch_alter_table('tipos_operacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_operacao_tenant_id'))

    op.drop_table('tipos_operacao')
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_tenant_id'))

    op.drop_table('funcionarios')
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formas_pagamento_tenant_id'))

    op.drop_table('formas_pagamento')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_tenant_id'))

    op.drop_table('empresas')
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupons_tenant_id'))

    op.drop_table('cupons')
    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_produto_tenant_id'))

    op.drop_table('categorias_produto')
    with op.batch_alter_table('categorias_financeiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_financeiras_tenant_id'))

    op.drop_table('categorias_financeiras')
    op.drop_table('tenants')
    # ### end Alembic commands ###
