"""v2

Revision ID: 9d1dca4d2bc5
Revises: 7f3c1a2b9d4e
Create Date: 2026-04-07 00:47:52.820766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1dca4d2bc5'
down_revision = '7f3c1a2b9d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_role_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###
